In [1]:
import pandas as pd
import numpy as np

In [2]:
raw=pd.read_csv(r'C:\Users\HP\Desktop\winequality-red.csv')
raw

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [3]:
df=raw.copy()

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [5]:
print(df.shape)

(1599, 12)


In [6]:
df['fixed acidity'].median()

7.9

In [7]:
df['fixed acidity'].unique()

array([ 7.4,  7.8, 11.2,  7.9,  7.3,  7.5,  6.7,  5.6,  8.9,  8.5,  8.1,
        7.6,  6.9,  6.3,  7.1,  8.3,  5.2,  5.7,  8.8,  6.8,  4.6,  7.7,
        8.7,  6.4,  6.6,  8.6, 10.2,  7. ,  7.2,  9.3,  8. ,  9.7,  6.2,
        5. ,  4.7,  8.4, 10.1,  9.4,  9. ,  8.2,  6.1,  5.8,  9.2, 11.5,
        5.4,  9.6, 12.8, 11. , 11.6, 12. , 15. , 10.8, 11.1, 10. , 12.5,
       11.8, 10.9, 10.3, 11.4,  9.9, 10.4, 13.3, 10.6,  9.8, 13.4, 10.7,
       11.9, 12.4, 12.2, 13.8,  9.1, 13.5, 10.5, 12.6, 14. , 13.7,  9.5,
       12.7, 12.3, 15.6,  5.3, 11.3, 13. ,  6.5, 12.9, 14.3, 15.5, 11.7,
       13.2, 15.9, 12.1,  5.1,  4.9,  5.9,  6. ,  5.5])

In [8]:
sorted(df['fixed acidity'].unique())

[4.6,
 4.7,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6,
 5.7,
 5.8,
 5.9,
 6.0,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 6.6,
 6.7,
 6.8,
 6.9,
 7.0,
 7.1,
 7.2,
 7.3,
 7.4,
 7.5,
 7.6,
 7.7,
 7.8,
 7.9,
 8.0,
 8.1,
 8.2,
 8.3,
 8.4,
 8.5,
 8.6,
 8.7,
 8.8,
 8.9,
 9.0,
 9.1,
 9.2,
 9.3,
 9.4,
 9.5,
 9.6,
 9.7,
 9.8,
 9.9,
 10.0,
 10.1,
 10.2,
 10.3,
 10.4,
 10.5,
 10.6,
 10.7,
 10.8,
 10.9,
 11.0,
 11.1,
 11.2,
 11.3,
 11.4,
 11.5,
 11.6,
 11.7,
 11.8,
 11.9,
 12.0,
 12.1,
 12.2,
 12.3,
 12.4,
 12.5,
 12.6,
 12.7,
 12.8,
 12.9,
 13.0,
 13.2,
 13.3,
 13.4,
 13.5,
 13.7,
 13.8,
 14.0,
 14.3,
 15.0,
 15.5,
 15.6,
 15.9]

In [9]:
fixed_columns=pd.get_dummies(df['fixed acidity'].unique())

In [10]:
fixed_columns=pd.get_dummies(df['fixed acidity'],drop_first=True)

In [11]:
df.columns.values

array(['fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'], dtype=object)

In [12]:
df=df.drop(['fixed acidity'],axis=1)
df.head(3)

volatile acidity  citric acid  residual sugar  chlorides  \
0              0.70         0.00             1.9      0.076   
1              0.88         0.00             2.6      0.098   
2              0.76         0.04             2.3      0.092   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5

In [13]:
low_fixed=fixed_columns.loc[:,1:7.9].max(axis=1)
high_fixed=fixed_columns.loc[:,8:].max(axis=1)

In [14]:
df=pd.concat([df,low_fixed,high_fixed],axis=1)
df.head(5)

volatile acidity  citric acid  residual sugar  chlorides  \
0              0.70         0.00             1.9      0.076   
1              0.88         0.00             2.6      0.098   
2              0.76         0.04             2.3      0.092   
3              0.28         0.56             1.9      0.075   
4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  0  1  
0      9.4        5  1  0  
1      9.8        5  1  0  
2      9.8        5  1  0  
3      9.8        6  0  1  
4      9.4        5  1  0

In [15]:
df.columns.values

array(['volatile acidity', 'citric acid', 'residual sugar', 'chlorides',
       'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH',
       'sulphates', 'alcohol', 'quality', 0, 1], dtype=object)

In [16]:
columns_names=(['volatile acidity', 'citric acid', 'residual sugar', 'chlorides',
       'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH',
       'sulphates', 'alcohol', 'quality', 'low_fixed','high_fixed'])

In [17]:
df.columns=columns_names
df.head(5)

volatile acidity  citric acid  residual sugar  chlorides  \
0              0.70         0.00             1.9      0.076   
1              0.88         0.00             2.6      0.098   
2              0.76         0.04             2.3      0.092   
3              0.28         0.56             1.9      0.075   
4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  low_fixed  high_fixed  
0      9.4        5          1           0  
1      9.8        5          1           0  
2      9.8        5          1           0  
3      9.8        6          0           1  
4      9.4        5          1           0

In [18]:
columns_names_reordered=(['low_fixed','high_fixed','volatile acidity', 'citric acid', 'residual sugar', 'chlorides',
       'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH',
       'sulphates', 'alcohol', 'quality',])

In [19]:
df=df[columns_names_reordered]
df.head(5)

low_fixed  high_fixed  volatile acidity  citric acid  residual sugar  \
0          1           0              0.70         0.00             1.9   
1          1           0              0.88         0.00             2.6   
2          1           0              0.76         0.04             2.3   
3          0           1              0.28         0.56             1.9   
4          1           0              0.70         0.00             1.9   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.076                 11.0                  34.0   0.9978  3.51   
1      0.098                 25.0                  67.0   0.9968  3.20   
2      0.092                 15.0                  54.0   0.9970  3.26   
3      0.075                 17.0                  60.0   0.9980  3.16   
4      0.076                 11.0                  34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [20]:
 df['volatile acidity'].median()

0.52

In [21]:
df['volatile acidity'].unique()

array([0.7  , 0.88 , 0.76 , 0.28 , 0.66 , 0.6  , 0.65 , 0.58 , 0.5  ,
       0.615, 0.61 , 0.62 , 0.56 , 0.59 , 0.32 , 0.22 , 0.39 , 0.43 ,
       0.49 , 0.4  , 0.41 , 0.71 , 0.645, 0.675, 0.685, 0.655, 0.605,
       0.38 , 1.13 , 0.45 , 0.67 , 0.52 , 0.935, 0.29 , 0.31 , 0.51 ,
       0.42 , 0.63 , 0.69 , 0.735, 0.725, 0.705, 0.785, 0.75 , 0.625,
       0.3  , 0.55 , 1.02 , 0.775, 0.9  , 0.545, 0.575, 0.33 , 0.54 ,
       1.07 , 0.695, 1.33 , 0.745, 1.04 , 0.715, 0.415, 0.34 , 0.68 ,
       0.95 , 0.53 , 0.64 , 0.885, 0.805, 0.73 , 0.37 , 0.835, 1.09 ,
       0.57 , 0.44 , 0.635, 0.82 , 0.48 , 1.   , 0.21 , 0.35 , 0.975,
       0.26 , 0.87 , 0.18 , 0.27 , 0.2  , 0.36 , 0.83 , 0.46 , 0.47 ,
       0.77 , 0.815, 0.795, 0.665, 0.765, 0.24 , 0.85 , 0.84 , 0.96 ,
       0.78 , 0.23 , 0.315, 0.365, 0.25 , 0.825, 0.72 , 0.595, 0.585,
       0.915, 0.755, 0.845, 1.24 , 0.8  , 0.98 , 1.185, 0.92 , 1.035,
       1.025, 0.565, 0.74 , 1.115, 0.865, 0.875, 0.965, 0.91 , 0.89 ,
       1.01 , 0.305,

In [22]:
volatile_columns=pd.get_dummies(df['volatile acidity'].unique())

In [23]:
volatile_columns=pd.get_dummies(df['volatile acidity'],drop_first=True)

In [24]:
df.columns.values

array(['low_fixed', 'high_fixed', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'], dtype=object)

In [25]:
df=df.drop(['volatile acidity'],axis=1)
df.head(3)

low_fixed  high_fixed  citric acid  residual sugar  chlorides  \
0          1           0         0.00             1.9      0.076   
1          1           0         0.00             2.6      0.098   
2          1           0         0.04             2.3      0.092   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5

In [26]:
low_volatile=volatile_columns.loc[:,0:0.52].max(axis=1)
high_volatile=volatile_columns.loc[:,0.52:].max(axis=1)

In [27]:
df=pd.concat([df,low_volatile,high_volatile],axis=1)
df.head(5)

low_fixed  high_fixed  citric acid  residual sugar  chlorides  \
0          1           0         0.00             1.9      0.076   
1          1           0         0.00             2.6      0.098   
2          1           0         0.04             2.3      0.092   
3          0           1         0.56             1.9      0.075   
4          1           0         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  0  1  
0      9.4        5  0  1  
1      9.8        5  0  1  
2      9.8        5  0  1  
3      9.8        6  1  0  
4      9.4        5  0  1

In [28]:
df.columns.values

array(['low_fixed', 'high_fixed', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide',
       'density', 'pH', 'sulphates', 'alcohol', 'quality', 0, 1],
      dtype=object)

In [29]:
columns_names=(['low_fixed', 'high_fixed', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide',
       'density', 'pH', 'sulphates', 'alcohol', 'quality', 'low_volatile','high_volatile'])

In [30]:
df.columns=columns_names
df.head(5)

low_fixed  high_fixed  citric acid  residual sugar  chlorides  \
0          1           0         0.00             1.9      0.076   
1          1           0         0.00             2.6      0.098   
2          1           0         0.04             2.3      0.092   
3          0           1         0.56             1.9      0.075   
4          1           0         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  low_volatile  high_volatile  
0      9.4        5             0              1  
1      9.8        5             0              1  
2      9.8        5             0              1  
3      9.8        6             1              0  
4      9.4        5             0              1

In [31]:
columns_names_reordered=(['low_fixed', 'high_fixed','low_volatile','high_volatile', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide',
       'density', 'pH', 'sulphates', 'alcohol', 'quality', ])

In [32]:
df=df[columns_names_reordered]
df.head(5)

low_fixed  high_fixed  low_volatile  high_volatile  citric acid  \
0          1           0             0              1         0.00   
1          1           0             0              1         0.00   
2          1           0             0              1         0.04   
3          0           1             1              0         0.56   
4          1           0             0              1         0.00   

   residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
0             1.9      0.076                 11.0                  34.0   
1             2.6      0.098                 25.0                  67.0   
2             2.3      0.092                 15.0                  54.0   
3             1.9      0.075                 17.0                  60.0   
4             1.9      0.076                 11.0                  34.0   

   density    pH  sulphates  alcohol  quality  
0   0.9978  3.51       0.56      9.4        5  
1   0.9968  3.20       0.68      9.8        5  
2   0.9970  3.26       0.65      9.8        5  
3   0.9980  3.16       0.58      9.8        6  
4   0.9978  3.51       0.56      9.4        5

In [33]:
df['residual sugar'].unique()

array([ 1.9 ,  2.6 ,  2.3 ,  1.8 ,  1.6 ,  1.2 ,  2.  ,  6.1 ,  3.8 ,
        3.9 ,  1.7 ,  4.4 ,  2.4 ,  1.4 ,  2.5 , 10.7 ,  5.5 ,  2.1 ,
        1.5 ,  5.9 ,  2.8 ,  2.2 ,  3.  ,  3.4 ,  5.1 ,  4.65,  1.3 ,
        7.3 ,  7.2 ,  2.9 ,  2.7 ,  5.6 ,  3.1 ,  3.2 ,  3.3 ,  3.6 ,
        4.  ,  7.  ,  6.4 ,  3.5 , 11.  ,  3.65,  4.5 ,  4.8 ,  2.95,
        5.8 ,  6.2 ,  4.2 ,  7.9 ,  3.7 ,  6.7 ,  6.6 ,  2.15,  5.2 ,
        2.55, 15.5 ,  4.1 ,  8.3 ,  6.55,  4.6 ,  4.3 ,  5.15,  6.3 ,
        6.  ,  8.6 ,  7.5 ,  2.25,  4.25,  2.85,  3.45,  2.35,  2.65,
        9.  ,  8.8 ,  5.  ,  1.65,  2.05,  0.9 ,  8.9 ,  8.1 ,  4.7 ,
        1.75,  7.8 , 12.9 , 13.4 ,  5.4 , 15.4 ,  3.75, 13.8 ,  5.7 ,
       13.9 ])

In [34]:
df['residual sugar'].median()

2.2

In [35]:
residual_columns=pd.get_dummies(df['residual sugar'].unique())

In [36]:
residual_columns=pd.get_dummies(df['residual sugar'],drop_first=True)

In [37]:
df.columns.values

array(['low_fixed', 'high_fixed', 'low_volatile', 'high_volatile',
       'citric acid', 'residual sugar', 'chlorides',
       'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH',
       'sulphates', 'alcohol', 'quality'], dtype=object)

In [38]:
df=df.drop(['residual sugar'],axis=1)
df.head(3)

low_fixed  high_fixed  low_volatile  high_volatile  citric acid  chlorides  \
0          1           0             0              1         0.00      0.076   
1          1           0             0              1         0.00      0.098   
2          1           0             0              1         0.04      0.092   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5

In [39]:
low_residual=residual_columns.loc[:,0:2.2].max(axis=1)
high_residual=residual_columns.loc[:,2.3:].max(axis=1)

In [40]:
df=pd.concat([df,low_residual,high_residual],axis=1)
df.head(5)

low_fixed  high_fixed  low_volatile  high_volatile  citric acid  chlorides  \
0          1           0             0              1         0.00      0.076   
1          1           0             0              1         0.00      0.098   
2          1           0             0              1         0.04      0.092   
3          0           1             1              0         0.56      0.075   
4          1           0             0              1         0.00      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  0  1  
0      9.4        5  1  0  
1      9.8        5  0  1  
2      9.8        5  0  1  
3      9.8        6  1  0  
4      9.4        5  1  0

In [41]:
df.columns.values

array(['low_fixed', 'high_fixed', 'low_volatile', 'high_volatile',
       'citric acid', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality', 0, 1], dtype=object)

In [42]:
columns_names=(['low_fixed', 'high_fixed', 'low_volatile', 'high_volatile',
       'citric acid', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality', 'low_residual', 'high_residual']) 

In [43]:
df.columns=columns_names
df.head(5)

low_fixed  high_fixed  low_volatile  high_volatile  citric acid  chlorides  \
0          1           0             0              1         0.00      0.076   
1          1           0             0              1         0.00      0.098   
2          1           0             0              1         0.04      0.092   
3          0           1             1              0         0.56      0.075   
4          1           0             0              1         0.00      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  low_residual  high_residual  
0      9.4        5             1              0  
1      9.8        5             0              1  
2      9.8        5             0              1  
3      9.8        6             1              0  
4      9.4        5             1              0

In [44]:
columns_names_reordered=(['low_fixed', 'high_fixed', 'low_volatile', 'high_volatile',
       'citric acid','low_residual', 'high_residual', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality', ]) 

In [45]:
df=df[columns_names_reordered]
df.head(5)

low_fixed  high_fixed  low_volatile  high_volatile  citric acid  \
0          1           0             0              1         0.00   
1          1           0             0              1         0.00   
2          1           0             0              1         0.04   
3          0           1             1              0         0.56   
4          1           0             0              1         0.00   

   low_residual  high_residual  chlorides  free sulfur dioxide  \
0             1              0      0.076                 11.0   
1             0              1      0.098                 25.0   
2             0              1      0.092                 15.0   
3             1              0      0.075                 17.0   
4             1              0      0.076                 11.0   

   total sulfur dioxide  density    pH  sulphates  alcohol  quality  
0                  34.0   0.9978  3.51       0.56      9.4        5  
1                  67.0   0.9968  3.20       0.68      9.8        5  
2                  54.0   0.9970  3.26       0.65      9.8        5  
3                  60.0   0.9980  3.16       0.58      9.8        6  
4                  34.0   0.9978  3.51       0.56      9.4        5

In [46]:
df['total sulfur dioxide'].median()

38.0

In [47]:
df['total sulfur dioxide'].unique()

array([ 34. ,  67. ,  54. ,  60. ,  40. ,  59. ,  21. ,  18. , 102. ,
        65. ,  29. , 145. , 148. , 103. ,  56. ,  71. ,  37. ,  23. ,
        11. ,  35. ,  16. ,  82. , 113. ,  83. ,  50. ,  15. ,  30. ,
        19. ,  87. ,  46. ,  14. , 114. ,  12. ,  96. , 119. ,  73. ,
        45. ,  10. , 110. ,  52. , 112. ,  39. ,  27. ,  94. ,  43. ,
        42. ,  80. ,  51. ,  61. , 136. ,  31. , 125. ,  24. , 140. ,
       133. ,  85. , 106. ,  22. ,  36. ,  69. ,  64. , 153. ,  47. ,
       108. , 111. ,  62. ,  28. ,  89. ,  13. ,  90. , 134. ,  99. ,
        26. ,  63. , 105. ,  20. , 141. ,  88. , 129. , 128. ,  86. ,
       121. , 101. ,  44. ,   8. ,  49. ,  38. , 143. , 144. , 127. ,
       126. , 120. ,  55. ,  93. ,  95. ,  41. ,  58. ,  72. ,  81. ,
       109. ,  33. ,  53. ,  98. ,  48. ,  70. ,  25. , 135. ,  92. ,
        74. ,  32. ,  77. , 165. ,  75. , 124. ,  78. , 122. ,  66. ,
        68. ,  17. ,  91. ,  76. , 151. , 142. , 116. , 149. ,  57. ,
       104. ,  84. ,

In [48]:
total_columns=pd.get_dummies(df['total sulfur dioxide'].unique())

In [49]:
total_columns=pd.get_dummies(df['total sulfur dioxide'],drop_first=True)

In [50]:
df.columns.values

array(['low_fixed', 'high_fixed', 'low_volatile', 'high_volatile',
       'citric acid', 'low_residual', 'high_residual', 'chlorides',
       'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH',
       'sulphates', 'alcohol', 'quality'], dtype=object)

In [51]:
df=df.drop(['total sulfur dioxide'],axis=1)
df.head(3)

low_fixed  high_fixed  low_volatile  high_volatile  citric acid  \
0          1           0             0              1         0.00   
1          1           0             0              1         0.00   
2          1           0             0              1         0.04   

   low_residual  high_residual  chlorides  free sulfur dioxide  density    pH  \
0             1              0      0.076                 11.0   0.9978  3.51   
1             0              1      0.098                 25.0   0.9968  3.20   
2             0              1      0.092                 15.0   0.9970  3.26   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5

In [52]:
low_total=total_columns.loc[:,0:38].max(axis=1)
high_total=total_columns.loc[:,39:].max(axis=1)

In [53]:
df=pd.concat([df,low_total,high_total],axis=1)
df.head(5)

low_fixed  high_fixed  low_volatile  high_volatile  citric acid  \
0          1           0             0              1         0.00   
1          1           0             0              1         0.00   
2          1           0             0              1         0.04   
3          0           1             1              0         0.56   
4          1           0             0              1         0.00   

   low_residual  high_residual  chlorides  free sulfur dioxide  density    pH  \
0             1              0      0.076                 11.0   0.9978  3.51   
1             0              1      0.098                 25.0   0.9968  3.20   
2             0              1      0.092                 15.0   0.9970  3.26   
3             1              0      0.075                 17.0   0.9980  3.16   
4             1              0      0.076                 11.0   0.9978  3.51   

   sulphates  alcohol  quality  0  1  
0       0.56      9.4        5  1  0  
1       0.68      9.8        5  0  1  
2       0.65      9.8        5  0  1  
3       0.58      9.8        6  0  1  
4       0.56      9.4        5  1  0

In [54]:
df.columns.values

array(['low_fixed', 'high_fixed', 'low_volatile', 'high_volatile',
       'citric acid', 'low_residual', 'high_residual', 'chlorides',
       'free sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality', 0, 1], dtype=object)

In [55]:
columns_names=(['low_fixed', 'high_fixed', 'low_volatile', 'high_volatile',
       'citric acid', 'low_residual', 'high_residual', 'chlorides',
       'free sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality', 'low_total','high_total'])

In [56]:
df.columns=columns_names
df.head(5)

low_fixed  high_fixed  low_volatile  high_volatile  citric acid  \
0          1           0             0              1         0.00   
1          1           0             0              1         0.00   
2          1           0             0              1         0.04   
3          0           1             1              0         0.56   
4          1           0             0              1         0.00   

   low_residual  high_residual  chlorides  free sulfur dioxide  density    pH  \
0             1              0      0.076                 11.0   0.9978  3.51   
1             0              1      0.098                 25.0   0.9968  3.20   
2             0              1      0.092                 15.0   0.9970  3.26   
3             1              0      0.075                 17.0   0.9980  3.16   
4             1              0      0.076                 11.0   0.9978  3.51   

   sulphates  alcohol  quality  low_total  high_total  
0       0.56      9.4        5          1           0  
1       0.68      9.8        5          0           1  
2       0.65      9.8        5          0           1  
3       0.58      9.8        6          0           1  
4       0.56      9.4        5          1           0

In [57]:
columns_names_reordered=(['low_fixed', 'high_fixed', 'low_volatile', 'high_volatile',
       'citric acid', 'low_residual', 'high_residual', 'chlorides',
       'free sulfur dioxide', 'low_total','high_total', 'density', 'pH', 'sulphates', 'alcohol',
       'quality',])

In [58]:
df=df[columns_names_reordered]
df.head(5)

low_fixed  high_fixed  low_volatile  high_volatile  citric acid  \
0          1           0             0              1         0.00   
1          1           0             0              1         0.00   
2          1           0             0              1         0.04   
3          0           1             1              0         0.56   
4          1           0             0              1         0.00   

   low_residual  high_residual  chlorides  free sulfur dioxide  low_total  \
0             1              0      0.076                 11.0          1   
1             0              1      0.098                 25.0          0   
2             0              1      0.092                 15.0          0   
3             1              0      0.075                 17.0          0   
4             1              0      0.076                 11.0          1   

   high_total  density    pH  sulphates  alcohol  quality  
0           0   0.9978  3.51       0.56      9.4        5  
1           1   0.9968  3.20       0.68      9.8        5  
2           1   0.9970  3.26       0.65      9.8        5  
3           1   0.9980  3.16       0.58      9.8        6  
4           0   0.9978  3.51       0.56      9.4        5

In [59]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3], dtype=int64)

In [60]:
df['quality'].median()

6.0

In [61]:
targets=np.where(df['quality']>
                df['quality'].median(),1,0)
targets

array([0, 0, 0, ..., 0, 0, 0])

In [63]:
df['quality']=targets
df.head(5)

low_fixed  high_fixed  low_volatile  high_volatile  citric acid  \
0          1           0             0              1         0.00   
1          1           0             0              1         0.00   
2          1           0             0              1         0.04   
3          0           1             1              0         0.56   
4          1           0             0              1         0.00   

   low_residual  high_residual  chlorides  free sulfur dioxide  low_total  \
0             1              0      0.076                 11.0          1   
1             0              1      0.098                 25.0          0   
2             0              1      0.092                 15.0          0   
3             1              0      0.075                 17.0          0   
4             1              0      0.076                 11.0          1   

   high_total  density    pH  sulphates  alcohol  quality  
0           0   0.9978  3.51       0.56      9.4        0  
1           1   0.9968  3.20       0.68      9.8        0  
2           1   0.9970  3.26       0.65      9.8        0  
3           1   0.9980  3.16       0.58      9.8        0  
4           0   0.9978  3.51       0.56      9.4        0

In [64]:
targets.sum()/targets.shape[0]

0.1357098186366479

In [65]:
unscaled_inputs=df.iloc[:,:-1]

In [66]:
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler
class CustomScaler(BaseEstimator,TransformerMixin):
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler=StandardScaler(copy,with_mean,with_std)
        self.columns=columns
        self.mean_=None
        self.var_=None
        
    def fit(self,x,y=None):
        self.scaler.fit(x[self.columns],y)
        self.mean_=np.mean(x[self.columns])
        self.var_=np.var(x[self.columns])
        return self
        
    def transform(self,x,y=None,copy=None):
        init_col_order=x.columns
        x_scaled=pd.DataFrame(self.scaler.transform(x[self.columns]),columns=self.columns)
        x_not_scaled=x.loc[:,~x.columns.isin(self.columns)]
        return pd.concat([x_not_scaled,x_scaled],axis=1)[init_col_order]
        

In [67]:
unscaled_inputs.columns.values

array(['low_fixed', 'high_fixed', 'low_volatile', 'high_volatile',
       'citric acid', 'low_residual', 'high_residual', 'chlorides',
       'free sulfur dioxide', 'low_total', 'high_total', 'density', 'pH',
       'sulphates', 'alcohol'], dtype=object)

In [68]:
columns_to_omit=['low_fixed','high_fixed','low_volatile','high_volatile','low_residual','high_residual','low_total','high_total']

In [69]:
columns_to_scale=[x for x in unscaled_inputs.columns.values]

In [70]:
wine_scaler=CustomScaler(columns_to_scale)

In [71]:
wine_scaler.fit(unscaled_inputs)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['low_fixed', 'high_fixed', 'low_volatile',
                      'high_volatile', 'citric acid', 'low_residual',
                      'high_residual', 'chlorides', 'free sulfur dioxide',
                      'low_total', 'high_total', 'density', 'pH', 'sulphates',
                      'alcohol'],
             copy=None, with_mean=None, with_std=None)

In [73]:
scaled_inputs=wine_scaler.transform(unscaled_inputs)

In [74]:
scaled_inputs

low_fixed  high_fixed  low_volatile  high_volatile  citric acid  \
0      0.980797   -0.979571     -1.017031       0.979571    -1.391472   
1      0.980797   -0.979571     -1.017031       0.979571    -1.391472   
2      0.980797   -0.979571     -1.017031       0.979571    -1.186070   
3     -1.019579    1.020855      0.983255      -1.020855     1.484154   
4      0.980797   -0.979571     -1.017031       0.979571    -1.391472   
...         ...         ...           ...            ...          ...   
1594   0.980797   -0.979571     -1.017031       0.979571    -0.980669   
1595   0.980797   -0.979571     -1.017031       0.979571    -0.877968   
1596   0.980797   -0.979571      0.983255      -1.020855    -0.723916   
1597   0.980797   -0.979571     -1.017031       0.979571    -0.775267   
1598   0.980797   -0.979571      0.983255      -1.020855     1.021999   

      low_residual  high_residual  chlorides  free sulfur dioxide  low_total  \
0         0.902764      -0.899346  -0.243707            -0.466193   0.972242   
1        -1.107709       1.111919   0.223875             0.872638  -1.028550   
2        -1.107709       1.111919   0.096353            -0.083669  -1.028550   
3         0.902764      -0.899346  -0.264960             0.107592  -1.028550   
4         0.902764      -0.899346  -0.243707            -0.466193   0.972242   
...            ...            ...        ...                  ...        ...   
1594      0.902764      -0.899346   0.053845             1.542054  -1.028550   
1595      0.902764      -0.899346  -0.541259             2.211469  -1.028550   
1596     -1.107709       1.111919  -0.243707             1.255161  -1.028550   
1597      0.902764      -0.899346  -0.264960             1.542054  -1.028550   
1598     -1.107709       1.111919  -0.434990             0.203223  -1.028550   

      high_total   density        pH  sulphates   alcohol  
0      -0.968598  0.558274  1.288643  -0.579207 -0.960246  
1       1.032420  0.028261 -0.719933   0.128950 -0.584777  
2       1.032420  0.134264 -0.331177  -0.048089 -0.584777  
3       1.032420  0.664277 -0.979104  -0.461180 -0.584777  
4      -0.968598  0.558274  1.288643  -0.579207 -0.960246  
...          ...       ...       ...        ...       ...  
1594    1.032420 -0.978765  0.899886  -0.461180  0.072294  
1595    1.032420 -0.862162  1.353436   0.601055  0.729364  
1596    1.032420 -0.533554  0.705508   0.542042  0.541630  
1597    1.032420 -0.676657  1.677400   0.305990 -0.209308  
1598    1.032420 -0.666057  0.511130   0.010924  0.541630  

[1599 rows x 15 columns]

In [75]:
scaled_inputs.shape

(1599, 15)

In [77]:
from sklearn.model_selection import train_test_split

train_test_split(scaled_inputs,targets)

[      low_fixed  high_fixed  low_volatile  high_volatile  citric acid  \
 530   -1.019579    1.020855      0.983255      -1.020855    -0.159061   
 1378   0.980797   -0.979571      0.983255      -1.020855    -0.621215   
 1261   0.980797   -0.979571     -1.017031       0.979571    -1.391472   
 657   -1.019579    1.020855      0.983255      -1.020855     1.638205   
 347   -1.019579    1.020855      0.983255      -1.020855     2.049009   
 ...         ...         ...           ...            ...          ...   
 589   -1.019579    1.020855      0.983255      -1.020855     1.124700   
 386    0.980797   -0.979571     -1.017031       0.979571    -0.056360   
 832   -1.019579    1.020855      0.983255      -1.020855     0.765247   
 684   -1.019579    1.020855     -1.017031       0.979571     0.251743   
 441   -1.019579    1.020855      0.983255      -1.020855     1.946308   
 
       low_residual  high_residual  chlorides  free sulfur dioxide  low_total  \
 530       0.902764      -0.8

In [78]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)
print(x_train.shape,y_train.shape)

(1279, 15) (1279,)


In [79]:
print(x_test.shape,y_test.shape)

(320, 15) (320,)


In [80]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [81]:
reg=LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [82]:
reg.score(x_train,y_train)

0.8835027365129007

In [83]:
model_outputs=reg.predict(x_train)
model_outputs==y_train

array([ True,  True,  True, ...,  True,  True,  True])

In [84]:
reg.intercept_

array([-2.71473373])

In [85]:
reg.coef_

array([[ 0.10033188,  0.19065403, -0.02140892, -0.30329506,  0.27428765,
         0.2883512 ,  0.33177676, -0.45596174,  0.07935871,  0.31962489,
        -0.13295685, -0.05493051, -0.09124542,  0.56541757,  1.01542584]])

In [86]:
feature_name=unscaled_inputs.columns.values

In [87]:
summary_table=pd.DataFrame(columns=['feature_name'],data=feature_name)
summary_table['coefficient']=np.transpose(reg.coef_)
summary_table

feature_name  coefficient
0             low_fixed     0.100332
1            high_fixed     0.190654
2          low_volatile    -0.021409
3         high_volatile    -0.303295
4           citric acid     0.274288
5          low_residual     0.288351
6         high_residual     0.331777
7             chlorides    -0.455962
8   free sulfur dioxide     0.079359
9             low_total     0.319625
10           high_total    -0.132957
11              density    -0.054931
12                   pH    -0.091245
13            sulphates     0.565418
14              alcohol     1.015426

In [88]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

feature_name  coefficient
0             Intercept    -2.714734
1             low_fixed     0.100332
2            high_fixed     0.190654
3          low_volatile    -0.021409
4         high_volatile    -0.303295
5           citric acid     0.274288
6          low_residual     0.288351
7         high_residual     0.331777
8             chlorides    -0.455962
9   free sulfur dioxide     0.079359
10            low_total     0.319625
11           high_total    -0.132957
12              density    -0.054931
13                   pH    -0.091245
14            sulphates     0.565418
15              alcohol     1.015426

In [89]:
summary_table['Odds_ratio']=np.exp(summary_table.coefficient)
summary_table

feature_name  coefficient  Odds_ratio
0             Intercept    -2.714734    0.066223
1             low_fixed     0.100332    1.105538
2            high_fixed     0.190654    1.210041
3          low_volatile    -0.021409    0.978819
4         high_volatile    -0.303295    0.738381
5           citric acid     0.274288    1.315593
6          low_residual     0.288351    1.334226
7         high_residual     0.331777    1.393442
8             chlorides    -0.455962    0.633838
9   free sulfur dioxide     0.079359    1.082593
10            low_total     0.319625    1.376611
11           high_total    -0.132957    0.875503
12              density    -0.054931    0.946551
13                   pH    -0.091245    0.912794
14            sulphates     0.565418    1.760183
15              alcohol     1.015426    2.760539

In [90]:
reg.score(x_test,y_test)

0.871875

In [91]:
predicted_proba=reg.predict_proba(x_test)
predicted_proba

array([[0.77149552, 0.22850448],
       [0.98656674, 0.01343326],
       [0.9960397 , 0.0039603 ],
       [0.96401491, 0.03598509],
       [0.6874839 , 0.3125161 ],
       [0.90921632, 0.09078368],
       [0.94625421, 0.05374579],
       [0.96748912, 0.03251088],
       [0.98895381, 0.01104619],
       [0.98832183, 0.01167817],
       [0.75463068, 0.24536932],
       [0.8470408 , 0.1529592 ],
       [0.94229158, 0.05770842],
       [0.96819399, 0.03180601],
       [0.99042783, 0.00957217],
       [0.97659985, 0.02340015],
       [0.55849581, 0.44150419],
       [0.60161416, 0.39838584],
       [0.97008234, 0.02991766],
       [0.85301549, 0.14698451],
       [0.99149029, 0.00850971],
       [0.3832398 , 0.6167602 ],
       [0.97797521, 0.02202479],
       [0.90807801, 0.09192199],
       [0.89851601, 0.10148399],
       [0.99050189, 0.00949811],
       [0.94012046, 0.05987954],
       [0.99731615, 0.00268385],
       [0.80355335, 0.19644665],
       [0.98761701, 0.01238299],
       [0.

In [92]:
predicted_proba.shape

(320, 2)

In [93]:
predicted_proba[:,1]

array([0.22850448, 0.01343326, 0.0039603 , 0.03598509, 0.3125161 ,
       0.09078368, 0.05374579, 0.03251088, 0.01104619, 0.01167817,
       0.24536932, 0.1529592 , 0.05770842, 0.03180601, 0.00957217,
       0.02340015, 0.44150419, 0.39838584, 0.02991766, 0.14698451,
       0.00850971, 0.6167602 , 0.02202479, 0.09192199, 0.10148399,
       0.00949811, 0.05987954, 0.00268385, 0.19644665, 0.01238299,
       0.0818287 , 0.00780269, 0.14873021, 0.05534084, 0.13824999,
       0.04879879, 0.06151967, 0.01611406, 0.04327165, 0.57605011,
       0.06806196, 0.00167998, 0.5706173 , 0.08065126, 0.87794777,
       0.01516406, 0.01961134, 0.29590728, 0.1792377 , 0.03163723,
       0.24600748, 0.05946831, 0.01035862, 0.03917312, 0.28753375,
       0.06590729, 0.17942028, 0.09504857, 0.03346523, 0.02677506,
       0.02903914, 0.01960682, 0.32170655, 0.0308904 , 0.13259274,
       0.03643808, 0.17604487, 0.01249076, 0.62862872, 0.18390894,
       0.02227128, 0.04702019, 0.03886479, 0.14054178, 0.01221